<a href="https://colab.research.google.com/github/ricky4918/Tensorflow-2.0-Deep-Learning-and-Artificial-Intelligence/blob/main/Recurrent%20Neural%20Network_Time%20Series_and_Sequence%20Data/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf 
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout, BatchNormalization, MaxPooling2D, SimpleRNN
from tensorflow.keras.optimizers import SGD,Adam
import pandas as pd
from sklearn.metrics import confusion_matrix
import itertools
from tensorflow.keras.models import Model

In [2]:
# N = number of samples
# T = Sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [7]:
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N,T,D)

In [8]:
X

array([[[ 0.26798507,  1.12155149, -0.14510374],
        [-0.90557895,  0.35114638, -2.57734277],
        [ 0.12252614, -1.65612611, -0.70052438],
        [ 1.42839432, -0.31365979, -0.37145796],
        [ 1.58764572,  0.04525383, -0.53985764],
        [-0.37454101, -0.77023127,  0.97375256],
        [-0.65094244, -0.34872249, -1.59614571],
        [-2.27872646,  0.62538622,  0.47072975],
        [ 0.6367497 ,  0.59943428,  2.33378501],
        [ 0.99834395, -0.22655347,  0.25180558]]])

In [9]:
M = 5
i = Input(shape = (T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [10]:
Yhat = model.predict(X)
print(Yhat)

[[-0.04046737  0.263453  ]]


In [11]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.layers[1].get_weights()

[array([[-0.14670902, -0.04153913, -0.30521488, -0.82509184,  0.6071866 ],
        [ 0.03621638, -0.38707104, -0.28982532,  0.04852837, -0.17109412],
        [-0.0605315 ,  0.8505636 ,  0.6771241 ,  0.3885284 , -0.5952591 ]],
       dtype=float32),
 array([[ 0.13223171,  0.20073363, -0.46242875, -0.8305343 ,  0.19645163],
        [-0.7953935 ,  0.38801506,  0.02166573,  0.06404689,  0.46067566],
        [-0.10705155, -0.58708775, -0.6836708 ,  0.29293585,  0.3010826 ],
        [-0.53294224, -0.5728874 ,  0.21794379, -0.43625712, -0.38723725],
        [-0.23318774,  0.36915866, -0.52037007,  0.17314465, -0.71314883]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [14]:
a,b,c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [17]:
Wx, Wh, bh =model.layers[1].get_weights()
Wo,bo = model.layers[2].get_weights()

In [21]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = []

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo
  Yhats.append(y)

  h_last = h


print(Yhats[-1])

[-0.04046732  0.26345303]
